import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import Categories from '../components/Categories';
import Header from '../components/Header';
import Navigation from '../components/Navigation';
import Products from '../components/Products';
import Search from '../components/Search';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Search />
        <Banner />
        <Categories />
        <Products />
        <Products />
        <Products />
        <Products />
        <Products />
        <Products />
        <Products />
        <Navigation />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
