import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import Categories from '../components/Categories';
import Header from '../components/Header';
import Products from '../components/Products';
import SubCategories from '../components/SubCategories';
import { makeSerializable } from '../lib/util';
import prisma from '../lib/prisma';
const Home: NextPage = (props) => {
  console.log(props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Banner />
        <Categories />
        <SubCategories />
        <Products />
      </main>

      <footer></footer>
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async () => {
  const user = await prisma.user.findMany({});
  return {
    props: { user: makeSerializable(user) },
  };
};
export default Home;
